Repository Yanolza-Miniproject/frontend, pull requests merged in 2023-11, with the labels that each got.

#2 Feat: 메인페이지 기본 레이아웃 업데이트
  src/App.tsx
  src/components/Common/Footer.tsx
  src/components/Common/Header.tsx
  src/components/Common/Layout.tsx
  src/index.css
  src/main.tsx
  src/pages/Main/index.tsx
Labels: enhancement

#7 Docs: 카트 마이페이지 목 데이터 작성
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/fe_issue_template.md
  src/mock/cart-list.ts
  src/mock/myPageData.ts
  vite.config.ts
Labels: documentation

#12 Feat: 장바구니 페이지 기본 레이아웃 완성, 유틸함수 추가
  package-lock.json
  package.json
  src/assets/checkbox.svg
  src/assets/exit.svg
  src/components/Cart/CartItem/CartItem.styles.ts
  src/components/Cart/CartItem/CartItem.type.ts
  src/components/Cart/CartItem/CartItems.utils.ts
  src/components/Cart/CartItem/index.tsx
  src/components/Cart/Checkbox/Checkbox.ts
  src/components/Cart/Checkbox/Checkbox.types.ts
  src/components/Cart/Checkbox/index.tsx
  src/components/Cart/Estimate/Estimate.styles.ts
  src/components/Cart/Estimate/Estimate.types.ts
  src/components/Cart/Estimate/Estimate.utils.ts
  src/components/Cart/Estimate/index.tsx
  src/mock/myPageData.ts
  src/pages/Cart/Cart.styles.ts
  src/pages/Cart/Cart.utils.ts
  src/pages/Cart/index.tsx
  src/store/purchaseAtom.ts
  src/types/index.ts
  src/utils/calculateNightCount.ts
  src/utils/calculateTotalPrice.ts
  src/utils/formatNumber.ts
Labels: enhancement

#14 Feat: Header, Footer, 메인페이지 UI 수정, 사이드바 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/font/NotoSans-Regular.woff2
  src/assets/image/hotel-default.jpg
  src/assets/image/logo.png
  src/assets/react.svg
  src/assets/svg/cart-icon.svg
  src/assets/svg/like-icon.svg
  src/assets/svg/liked-icon.svg
  src/assets/svg/search-icon.svg
  src/assets/svg/signup-icon.svg
  src/assets/svg/totop-icon.svg
  src/assets/svg/user-icon.svg
  src/components/Common/Common.styles.ts
  src/components/Common/Footer.tsx
  src/components/Common/Header.tsx
  src/components/Common/Layout.tsx
  src/components/Common/Sidebar.tsx
  src/mock/mainPageData.ts
  src/pages/Main/Main.styles.ts
  src/pages/Main/Main.types.ts
  src/pages/Main/index.tsx
Labels: enhancement

#16 Feat: 버튼 공통 컴포넌트 추가
  src/components/Cart/Estimate/index.tsx
  src/components/Common/Button.tsx
Labels: enhancement

#19 Feat: 상세 페이지(객실) UI
  package-lock.json
  package.json
  src/components/Detail/ActionButtonGroup/ActionButtonGroup.styles.ts
  src/components/Detail/ActionButtonGroup/ActionButtonGroup.types.ts
  src/components/Detail/ActionButtonGroup/index.tsx
  src/components/Detail/Calendar/Calendar.css
  src/components/Detail/Calendar/Calendar.styles.ts
  src/components/Detail/Calendar/Calendar.types.ts
  src/components/Detail/Calendar/index.tsx
  src/components/Detail/PriceDisplay/PriceDisplay.styles.ts
  src/components/Detail/PriceDisplay/PriceDisplay.types.ts
  src/components/Detail/PriceDisplay/index.tsx
  src/components/Detail/ProductDetails/ProductDetail.styles.ts
  src/components/Detail/ProductDetails/ProductDetail.types.ts
  src/components/Detail/ProductDetails/index.tsx
  src/components/Detail/ProductGallery/ProductGallery.styles.ts
  src/components/Detail/ProductGallery/ProductGallery.types.ts
  src/components/Detail/ProductGallery/index.tsx
  src/components/Detail/QuantitySelector/QuantitySelector.styles.ts
  src/components/Detail/QuantitySelector/QuantitySelector.types.ts
  src/components/Detail/QuantitySelector/index.tsx
  src/components/Detail/StockStatusBaner/StockStatusBanner.styles.ts
  src/components/Detail/StockStatusBaner/StockStatusBanner.types.ts
  src/components/Detail/StockStatusBaner/index.tsx
  src/pages/Detail/Detail.styles.ts
  src/pages/Detail/index.tsx
Labels: enhancement

#21 Feat: 버튼 액션 추가, 빈 카트 화면 컴포넌트 추가, 리코일 총 가격 저장
  src/components/Cart/CartZero/CartZero.styles.ts
  src/components/Cart/CartZero/index.tsx
  src/components/Cart/Estimate/Estimate.utils.ts
  src/components/Cart/Estimate/index.tsx
  src/components/Common/Button.tsx
  src/pages/Cart/Cart.styles.ts
  src/pages/Cart/index.tsx
  src/store/purchaseAtom.ts
Labels: enhancement

#22 Feat : 카테고리 필터링 및 검색 무한 쿼리
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/Category/index.tsx
  src/assets/svg/Category_heart_icon.svg
  src/components/Category/CategoryBanner/CategoryBanner.styles.ts
  src/components/Category/CategoryBanner/index.tsx
  src/components/Category/CategoryFilter/CategoryFilter.constants.ts
  src/components/Category/CategoryFilter/CategoryFilter.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.types.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryFilter/index.tsx
  src/components/Category/CategoryItemWrapper/index.tsx
  src/components/Category/CatgoryItem/CategoryItem.styles.ts
  src/components/Category/CatgoryItem/index.tsx
  src/components/Category/HeartClick/HeartClick.styles.ts
  src/components/Category/HeartClick/HeartIcon/HeartIcon.styles.ts
  src/components/Category/HeartClick/HeartIcon/index.tsx
  src/components/Category/HeartClick/index.tsx
  src/components/Category/InfiniteScroller/InfiniteScroller.styles.ts
  src/components/Category/InfiniteScroller/index.tsx
  src/components/Category/SearchButton/SearchButton.styles.ts
  src/components/Category/SearchButton/index.tsx
  src/components/Common/Button.tsx
  src/hooks/useCategoryInfiniteQuery.ts
  src/main.tsx
  src/mocks/browser/browser.ts
  src/mocks/browser/constant.ts
  src/mocks/browser/handlers.ts
  src/pages/Category/Category.styles.ts
  src/pages/Category/Category.types.ts
  src/pages/Category/index.tsx
  src/store/categoryQueryAtom.ts
  tsconfig.json
  tsconfig.node.json
Labels: enhancement

#27 Feat: 결제하기 유효성검사 기능 구현
  src/components/MyPage/MyOrder/Header/index.tsx
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.styles.ts
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.types.ts
  src/components/MyPage/MyOrder/MyOrderItem/index.tsx
  src/components/MyPage/MyOrder/MyOrderList/MyOrderList.styles.ts
  src/components/MyPage/MyOrder/MyOrderList/index.tsx
  src/components/Payment/Btn/Btn.styles.ts
  src/components/Payment/Btn/index.tsx
  src/components/Payment/Item/Item.styles.ts
  src/components/Payment/Item/Item.types.ts
  src/components/Payment/Item/index.tsx
  src/components/Payment/ItemList/ItemList.styles.ts
  src/components/Payment/ItemList/ItemList.types.ts
  src/components/Payment/ItemList/index.tsx
  src/components/Payment/TermsAndConditions/TermsAndConditions.styles.ts
  src/components/Payment/TermsAndConditions/TermsAndConditions.types.ts
  src/components/Payment/TermsAndConditions/index.tsx
  src/components/Payment/TotalPrice/TotalPrice.styles.ts
  src/components/Payment/TotalPrice/index.tsx
  src/mock/myPageData.ts
  src/pages/Payment/Payment.styles.ts
  src/pages/Payment/index.tsx
  src/store/purchaseAtom.ts
Labels: enhancement

#31 Feat : 좋아요 클릭 시 구동하는 커스텀 훅 제작 pr
  src/api/Category/index.tsx
  src/components/Category/HeartClick/HeartIcon/HeartIcon.styles.ts
  src/components/Category/HeartClick/index.tsx
  src/hooks/useWishControl.ts
  src/mocks/browser/handlers.ts
Labels: enhancement

#34 Feat: 검색 페이지 UI 작성
  src/App.tsx
  src/assets/image/type0.png
  src/assets/image/type1.jpeg
  src/assets/image/type2.jpg
  src/assets/image/type3.jpg
  src/assets/image/type4.jpg
  src/assets/image/type5.jpg
  src/assets/image/type6.png
  src/assets/image/type7.jpg
  src/assets/image/type8.png
  src/assets/image/type9.png
  src/assets/svg/accom-icon.svg
  src/assets/svg/map-icon.svg
  src/assets/svg/option-icon.svg
  src/assets/svg/option0.svg
  src/assets/svg/option1.svg
  src/assets/svg/option2.svg
  src/assets/svg/reset-btn.svg
  src/components/Common/Common.styles.ts
  src/components/Search/Button/Button.styles.ts
  src/components/Search/Button/Button.types.ts
  src/components/Search/Button/index.tsx
  src/pages/Search/Search.styles.ts
  src/pages/Search/Search.types.ts
  src/pages/Search/Search.utils.ts
  src/pages/Search/index.tsx
Labels: enhancement

#37 Fix: 스타일 크기 단위 rem으로 수정, 오타 수정
  src/components/Cart/CartItem/CartItem.styles.ts
  src/components/Cart/CartItem/index.tsx
  src/components/Cart/CartZero/CartZero.styles.ts
  src/components/Cart/Checkbox/Checkbox.ts
  src/components/Cart/Estimate/Estimate.styles.ts
  src/components/Cart/Estimate/index.tsx
  src/components/Complete/CompleteMessage/CompleteMessage.styles.ts
  src/mock/myPageData.ts
  src/pages/Cart/Cart.styles.ts
  src/pages/Cart/index.tsx
  src/pages/Complete/Complete.styles.ts
  src/pages/Search/index.tsx
  src/types/index.ts
Labels: Fix

#41 Chore : jest 설치 및 기본 설정
  babel.config.cjs
  jest.config.cjs
  jest.setup.ts
  package-lock.json
  package.json
  setup.ts
  src/App.tsx
  src/api/MyPage/index.ts
  src/api/MyPage/query.ts
  src/components/Category/HeartClick/HeartIcon/index.test.tsx
  src/hooks/useAllGetQuery.ts
  src/mocks/browser/handlers.ts
  src/pages/MyPage/MyWishs/MyWishs.styles.ts
  src/pages/MyPage/MyWishs/index.tsx
  tsconfig.json
Labels: Chore

#42 Feat : jest + react-testing-library 개발 경험 공유 및 예시 코드 작성
  src/components/Category/HeartClick/index.test.tsx
  src/components/Category/HeartClick/index.tsx
Labels: Enhancement

#44 Fix: jest SVG import하는 파일 안되는 문제
  jest.config.cjs
  package-lock.json
  package.json
  src/components/Cart/CartList/CartList.styles.ts
  src/components/Cart/CartList/CartList.test.tsx
  src/components/Cart/CartList/CartList.types.ts
  src/components/Cart/CartList/CartLust.utils.ts
  src/components/Cart/CartList/index.tsx
  src/pages/Cart/index.tsx
Labels: Enhancement

#47 Feat: 장바구니 페이지 로딩, 데이터 아이템 렌더링 테스트 추가
  src/components/Cart/CartItem/CartItems.utils.ts
  src/components/Cart/CartItem/index.tsx
  src/components/Cart/CartList/CartList.test.tsx
  src/components/Cart/CartList/CartList.types.ts
  src/components/Cart/CartList/CartList.utils.ts
  src/components/Cart/CartList/index.tsx
  src/pages/Cart/Cart.test.tsx
  src/pages/Cart/index.tsx
Labels: Test

#48 Feat: 객실 상세 페이지 리코일, msw 연결
  src/components/Detail/ActionButtonGroup/index.tsx
  src/components/Detail/Calendar/Calendar.types.ts
  src/components/Detail/Calendar/index.tsx
  src/components/Detail/PriceDisplay/index.tsx
  src/components/Detail/ProductDetails/ProductDetail.types.ts
  src/components/Detail/QuantitySelector/index.tsx
  src/hooks/useDetailFetch.ts
  src/mock/detailPageData.ts
  src/mocks/browser/handlers.ts
  src/pages/Detail/index.tsx
  src/store/checkinCheckOutAtom.ts
  src/store/dateState.ts
  src/utils/formatDate.ts
Labels: Enhancement

#45 Feat : MyWish 페이지 제작 및 TDD 진행
  package-lock.json
  package.json
  src/api/MyPage/index.ts
  src/components/Category/CatgoryItem/CategoryItem.styles.ts
  src/components/Category/CatgoryItem/index.test.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/MyPage/MyList/index.tsx
  src/components/MyPage/MyWish/MyWishHeader/MyWIshHeader.styles.ts
  src/components/MyPage/MyWish/MyWishHeader/index.test.tsx
  src/components/MyPage/MyWish/MyWishHeader/index.tsx
  src/components/MyPage/MyWish/MyWishList/MyWishList.styles.ts
  src/components/MyPage/MyWish/MyWishList/index.test.tsx
  src/components/MyPage/MyWish/MyWishList/index.tsx
  src/pages/MyPage/MyWishs/MyWishs.styles.ts
  src/pages/MyPage/MyWishs/index.tsx
  src/test/test.utils.tsx
Labels: Enhancement

#53 Feat: 장바구니 아이템 선택 관련 테스트 추가, api 데이터 최신화
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Cart/CartList/CartList.test.tsx
  src/components/Cart/Estimate/index.tsx
  src/hooks/useCartFetch.ts
  src/mocks/browser/handlers.ts
  src/pages/Cart/index.tsx
  src/pages/NotFound/index.tsx
  tsconfig.json
Labels: Fix, Test

#56 Feat: 결제하기/ 결제내역 페이지 api 업데이트 건 반영
  package-lock.json
  src/components/MyPage/MyList/index.tsx
  src/components/MyPage/MyOrder/Header/index.tsx
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.styles.ts
  src/components/MyPage/MyOrder/MyOrderItem/index.tsx
  src/components/MyPage/MyOrder/MyOrderList/index.tsx
  src/components/Payment/Btn/index.tsx
  src/hooks/usePayment.ts
  src/mock/myPageData.ts
  src/mocks/browser/handlers.ts
Labels: Enhancement

#59 Feat : Category Test 코드 작성 완료
  .husky/pre-commit
  jest.config.cjs
  jest.setup.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Category/CategoryBanner/CategoryBanner.styles.ts
  src/components/Category/CategoryBanner/index.test.tsx
  src/components/Category/CategoryBanner/index.tsx
  src/components/Category/CategoryFilter/CategoryFilter.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.test.tsx
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryFilter/index.test.tsx
  src/components/Category/CategoryItemWrapper/CategoryItemWrapper.styles.ts
  src/components/Category/CategoryItemWrapper/index.test.tsx
  src/components/Category/CategoryItemWrapper/index.tsx
  src/components/Category/CategoryQuery/index.test.tsx
  src/components/Category/CategoryQuery/index.tsx
  src/components/Category/HeartClick/index.test.tsx
  src/components/Category/InfiniteScroller/InfiniteScroller.styles.ts
  src/components/Category/InfiniteScroller/index.tsx
  src/components/Category/SearchButton/SearchButton.styles.ts
  src/components/Category/SearchButton/index.test.tsx
  src/components/MyPage/MyWish/MyWishList/index.test.tsx
  src/hooks/useCategoryInfiniteQuery.ts
  src/pages/Category/Category.styles.ts
  src/test/test.utils.tsx
Labels: Test

#60 Feat: 기존 코드 수정, 메인페이지 msw 연결
  public/mockServiceWorker.js
  src/assets/svg/like-icon.svg
  src/assets/svg/liked-icon.svg
  src/assets/svg/totop-icon.svg
  src/components/Common/Common.styles.ts
  src/components/Common/Sidebar.tsx
  src/components/Search/Button/Button.styles.ts
  src/components/Search/Button/index.tsx
  src/hooks/useMainListFetch.ts
  src/pages/Main/Main.styles.ts
  src/pages/Main/index.tsx
  src/pages/Search/Search.styles.ts
Labels: Enhancement

#64 Feat : Results 페이지 테스트 코드 작성 및 detail page 라우팅
  .github/ISSUE_TEMPLATE/fe_pull_request_template.md
  package-lock.json
  package.json
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CatgoryItem/CategoryItem.styles.ts
  src/components/Category/CatgoryItem/index.test.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/Detail/Calendar/index.tsx
  src/components/Detail/PriceDisplay/index.tsx
  src/components/DetailList/BookingCalendar/index.tsx
  src/components/DetailList/DateSelector/index.tsx
  src/components/SearchListBanner/index.test.tsx
  src/components/SearchListBanner/index.tsx
  src/hooks/useGetValidParams.ts
  src/test/test.utils.tsx
  src/utils/filterTextDecoder.ts
Labels: Fix, Test, Enhancement

#68 Feat: 결제하기, 결제내역페이지 테스트 코드 작성
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/MyPage/MyOrder/Header/index.tsx
  src/components/MyPage/MyOrder/MyOrderList/MyOrderList.test.tsx
  src/components/MyPage/MyOrder/MyOrderList/index.tsx
  src/components/Payment/Btn/Btn.test.tsx
  src/components/Payment/Btn/index.tsx
  src/components/Payment/TermsAndConditions/TermsAndConditions.test.tsx
  src/components/Payment/TermsAndConditions/index.tsx
  src/pages/Payment/Payment.test.tsx
  src/pages/Payment/index.tsx
Labels: Fix, Test, Refactoring

#70 Fix : atom Name 수정
  src/components/DetailList/RoomList/index.tsx
Labels: Fix

#71 Fix : 라우팅 설정 변경 (error페이지 라우팅)
  package.json
Labels: Fix, Deploy

#75 Feat : firebase 자동배포 설정
  .firebase/hosting.ZGlzdA.cache
  .firebase/hosting.cHVibGlj.cache
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  package-lock.json
  package.json
  tsconfig.node.json
  vite.config.ts
Labels: Deploy

#76 Feat : workflow 파일 pr용 삭제
  .github/workflows/firebase-hosting-pull-request.yml
Labels: Deploy

#73 Refactoring: 검색페이지 컴포넌트 분할 및 hooks 생성
  src/components/Search/SearchParamsDisplay/SearchParamsDisplay.styles.ts
  src/components/Search/SearchParamsDisplay/index.tsx
  src/components/Search/SearchSelector/SearchOptions/index.tsx
  src/components/Search/SearchSelector/SearchRegion/index.tsx
  src/components/Search/SearchSelector/SearchSelector.styles.ts
  src/components/Search/SearchSelector/SearchSelector.types.ts
  src/components/Search/SearchSelector/SearchType/index.tsx
  src/hooks/useSearchHandler.ts
  src/hooks/useSendSearchQuery.ts
  src/pages/Search/Search.styles.ts
  src/pages/Search/Search.types.ts
  src/pages/Search/index.tsx
  src/store/searchSelectorAtom.ts
  src/store/searchSelectorData.ts
Labels: Fix, Refactoring

#78 Feat: 공통 axios 인스턴스 생성
  .gitignore
  src/hooks/useAxios.ts
  src/hooks/useCartFetch.ts
Labels: Enhancement

#79 Design: 로고, 파비콘, 공통문구, 사이드바 업데이트
  index.html
  public/vite.svg
  src/assets/svg/logo.svg
  src/components/Category/CategoryBanner/index.test.tsx
  src/components/Common/Common.styles.ts
  src/components/Common/Header.tsx
  src/components/Common/Sidebar.tsx
  src/components/MyPage/MyOrder/MyOrderList/index.tsx
  src/hooks/usePayment.ts
  src/pages/Category/index.tsx
  src/pages/Main/index.tsx
Labels: Refactoring, Design

#80 Feat: 사용자 위치 정보 받아오기
  src/hooks/useGeolocation.ts
  src/pages/Cart/index.tsx
Labels: Enhancement

#87 Feat : 배포환경 api 통신 가능한 지 test
  babel.config.cjs
  jest.config.cjs
  package-lock.json
  package.json
  src/api/Category/index.tsx
  src/components/Category/CategoryBanner/CategoryBanner.types.ts
  src/components/Category/CategoryBanner/index.tsx
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.types.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryItemWrapper/CategoryItemWrapper.types.ts
  src/components/Category/CategoryItemWrapper/index.tsx
  src/components/Category/CategoryQuery/CategoryQuery.types.ts
  src/components/Category/CategoryQuery/index.test.tsx
  src/components/Category/CategoryQuery/index.tsx
  src/components/Category/CatgoryItem/CategoryItem.styles.ts
  src/components/Category/CatgoryItem/CategoryItem.types.ts
  src/components/Category/CatgoryItem/index.test.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/Category/HeartClick/HeartClick.types.ts
  src/components/Category/HeartClick/index.tsx
  src/components/MyPage/MyWish/MyWishList/index.test.tsx
  src/components/Search/SearchSelector/SearchSelector.types.ts
  src/components/SearchListBanner/index.test.tsx
  src/hooks/useAxios.ts
  src/hooks/useCategoryInfiniteQuery.ts
  src/hooks/useGetValidParams.ts
  src/main.tsx
  src/mock/myPageData.ts
  src/mocks/browser/constant.ts
  src/mocks/browser/handlers.ts
  src/pages/Category/Category.types.ts
  src/pages/SearchList/index.tsx
  src/pages/Signin/index.test.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.test.tsx
  src/pages/Signup/index.tsx
  src/test/test.utils.tsx
  src/utils/filterDecoder.ts
  src/utils/filterTextDecoder.ts
  tsconfig.json
  tsconfig.node.json
Labels: Deploy

#88 Feat : target test2
  vite.config.ts
Labels: Deploy

#89 Test : api 요청 가능한 지 test
  src/api/Category/index.tsx
  src/components/Common/Header.tsx
  src/pages/Signup/index.tsx
  vite.config.ts
Labels: Deploy

#90 Feat : test 주소 변경 후 test
  src/api/Category/index.tsx
  src/pages/Signup/index.tsx
Labels: Deploy

#91 Feat : 도메인 주소 변경 후 test
  src/pages/Signin/index.tsx
  vite.config.ts
Labels: Deploy

#92 Feat : https 통신 test
  src/api/Category/index.tsx
  src/main.tsx
  src/mocks/browser/handlers.ts
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  vite.config.ts
Labels: Deploy

#93 Feat : http 프록시 제거 test
  src/api/Category/index.tsx
  src/pages/Signup/index.tsx
Labels: Deploy

#86 Feat: 메인/검색페이지 테스트코드 추가 및 메인페이지 리팩토링
  public/mockServiceWorker.js
  src/components/Common/Common.styles.ts
  src/components/Common/Sidebar.test.tsx
  src/components/Main/AccommodationList/AccommodationList.styles.ts
  src/components/Main/AccommodationList/AccommodationList.types.ts
  src/components/Main/AccommodationList/index.test.tsx
  src/components/Main/AccommodationList/index.tsx
  src/components/Search/Button/Button.styles.ts
  src/components/Search/Button/index.test.tsx
  src/components/Search/SearchParamsDisplay/index.test.tsx
  src/components/Search/SearchSelector/SearchOptions/index.test.tsx
  src/components/Search/SearchSelector/SearchRegion/index.test.tsx
  src/components/Search/SearchSelector/SearchType/index.test.tsx
  src/hooks/useMainListFetch.ts
  src/pages/Main/Main.styles.ts
  src/pages/Main/Main.types.ts
  src/pages/Main/index.test.tsx
  src/pages/Main/index.tsx
Labels: Test, Refactoring

#100 Feat: 숙소페이지/ 객실페이지 API 연동 중
  src/components/Detail/ActionButtonGroup/index.tsx
  src/components/Detail/Calendar/index.tsx
  src/components/Detail/PriceDisplay/index.tsx
  src/components/Detail/QuantitySelector/index.tsx
  src/components/DetailList/BookingCalendar/index.test.tsx
  src/components/DetailList/Card/index.test.tsx
  src/components/DetailList/Card/index.tsx
  src/components/DetailList/CardList/index.test.tsx
  src/components/DetailList/CardList/index.tsx
  src/components/DetailList/DateSelector/index.test.tsx
  src/components/DetailList/ProductImage/index.test.tsx
  src/components/DetailList/ProductInfo/index.test.tsx
  src/components/DetailList/ProductTitle/index.test.tsx
  src/components/DetailList/RoomItem/RoomItem.types.ts
  src/components/DetailList/RoomItem/index.test.tsx
  src/components/DetailList/RoomItem/index.tsx
  src/components/DetailList/RoomList/RoomList.types.ts
  src/components/DetailList/RoomList/index.test.tsx
  src/components/DetailList/RoomList/index.tsx
  src/hooks/useDetailFetch.ts
  src/pages/Detail/Detail.types.ts
  src/pages/Detail/index.tsx
  src/pages/DetailList/DetailList.types.ts
  src/pages/DetailList/index.tsx
Labels: Enhancement

#101 Fix: 메인페이지 링크 수정
  src/components/Main/AccommodationList/index.tsx
Labels: Fix

#105 Feat : 로그인, 로그아웃 api 연동
  src/api/Auth/index.tsx
  src/api/Auth/query.ts
  src/api/Category/index.tsx
  src/api/MyPage/index.ts
  src/components/Category/CategoryBanner/index.tsx
  src/components/Payment/Btn/index.tsx
  src/hooks/useAxios.ts
  src/main.tsx
  src/pages/Cart/index.tsx
  src/pages/Signin/Signin.styles.ts
  src/pages/Signin/index.test.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/Signup.styles.ts
  src/pages/Signup/index.test.tsx
  src/pages/Signup/index.tsx
  src/utils/getTokenRefresh.ts
Labels: Enhancement, Deploy

#109 Fix: 결제 완료 페이지 데이터 수
  src/components/Cart/CartItem/index.tsx
  src/components/Cart/CartList/index.tsx
  src/components/Cart/Estimate/index.tsx
  src/components/Complete/CompleteMessage/CompleteMessage.utils.ts
  src/hooks/useCartFetch.ts
  src/pages/Cart/index.tsx
  src/pages/Complete/index.tsx
Labels: Fix

#110 Feat: detailList 페이지의 RoomList 연동
  src/components/DetailList/ProductTitle/ProductTitle.types.ts
  src/components/DetailList/ProductTitle/index.tsx
  src/components/DetailList/RoomList/index.tsx
  src/pages/DetailList/index.tsx
Labels: Enhancement

#112 Fix: 테스트 코드의 데이터 이름 수정 완료했습니다.
  src/components/Cart/CartItem/CartItem.test.tsx
  src/components/Cart/CartList/CartList.test.tsx
  src/components/Cart/Estimate/Estimate.test.tsx
  src/components/Complete/CompleteMessage/CompleteMessage.test.tsx
  src/components/Complete/PaymentItems/PaymentItems.test.tsx
Labels: Fix

#113 Feat: 결제내역 페이지 API 연동
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.types.ts
  src/components/MyPage/MyOrder/MyOrderItem/index.tsx
  src/components/MyPage/MyOrder/MyOrderItemWrapper/MyOrderItemWrapper.styles.ts
  src/components/MyPage/MyOrder/MyOrderItemWrapper/MyOrderItemWrapper.types.ts
  src/components/MyPage/MyOrder/MyOrderItemWrapper/index.tsx
  src/components/MyPage/MyOrder/MyOrderList/MyOrderList.type.ts
  src/components/MyPage/MyOrder/MyOrderList/index.tsx
  src/components/Payment/Btn/index.tsx
  src/components/Payment/ItemList/index.tsx
  src/hooks/usePayment.ts
  src/pages/MyPage/MyOrder/index.tsx
Labels: Enhancement

#115 Feat : 불필요한 alert 제거
  src/api/Auth/index.tsx
  src/components/Category/CategoryBanner/CategoryBanner.styles.ts
  src/components/Category/CategoryFilter/CategoryFilter.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryFilter/index.tsx
  src/components/Category/CategoryItemWrapper/CategoryItemWrapper.styles.ts
  src/components/Category/CatgoryItem/index.test.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/Main/AccommodationList/index.tsx
  src/hooks/useAxios.ts
  src/main.tsx
  src/mocks/browser/constant.ts
  src/mocks/browser/handlers.ts
  src/pages/Category/Category.styles.ts
  src/pages/Category/Category.types.ts
  src/pages/Category/index.tsx
  src/test/test.utils.tsx
  src/utils/getTokenRefresh.ts
Labels: Fix

#116 Feat: 객실 페이지 품절, 품절 임박 배너 연동
  src/components/Detail/StockStatusBaner/StockStatusBanner.styles.ts
  src/components/Detail/StockStatusBaner/index.tsx
  src/pages/Detail/Detail.types.ts
  src/pages/Detail/index.tsx
Labels: Enhancement

#118 Feat: 공통 컴포넌트 (Header 업데이트)
  src/assets/svg/cart-icon.svg
  src/assets/svg/loader.svg
  src/assets/svg/loader1.svg
  src/assets/svg/logout-icon.svg
  src/assets/svg/search-icon.svg
  src/assets/svg/signin-icon.svg
  src/assets/svg/signup-icon.svg
  src/assets/svg/user-icon.svg
  src/components/Common/Common.styles.ts
  src/components/Common/Header.tsx
  src/components/Common/Loader.tsx
Labels: Enhancement, Design

#119 Feat: 장바구니 반응형 추가, vercel 설정 추가
  src/components/Cart/CartItem/CartItem.styles.ts
  src/components/Cart/CartList/CartList.styles.ts
  src/components/Complete/CompleteMessage/CompleteMessage.styles.ts
  vercel.json
Labels: Fix, Enhancement

#123 Feat : 불필요한 alert제거 및 유저 atom 추가
  src/api/Auth/index.tsx
  src/api/Auth/query.ts
  src/api/Category/index.tsx
  src/components/Category/CategoryBanner/CategoryBanner.styles.ts
  src/components/Category/CategoryFilter/CategoryFilter.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/CategoryFilterPopUp.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.test.tsx
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryFilter/index.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/Common/Header.tsx
  src/hooks/useAxios.ts
  src/hooks/useWishControl.ts
  src/pages/Category/Category.styles.ts
  src/store/userDataAtom.ts
  src/utils/getTokenRefresh.ts
  src/utils/isLogined.ts
  src/utils/setSessionStorage.ts
Labels: Fix, Enhancement

#127 Feat: 결제완료시 complete이동시키는 로직 추가, 마이페이지내 이름 노출, 사진에러처리 일부 완성
  src/assets/image/empty.png
  src/assets/image/empty_large.png
  src/assets/image/empty_medium.png
  src/components/Cart/CartItem/index.tsx
  src/components/Category/CatgoryItem/index.tsx
  src/components/Detail/ProductGallery/index.tsx
  src/components/DetailList/ProductImage/index.tsx
  src/components/DetailList/RoomItem/index.tsx
  src/components/Main/AccommodationList/index.tsx
  src/components/MyPage/Header/index.tsx
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.styles.ts
  src/components/MyPage/MyOrder/MyOrderItem/index.tsx
  src/components/MyPage/MyOrder/MyOrderItemWrapper/MyOrderItemWrapper.styles.ts
  src/components/MyPage/MyOrder/MyOrderItemWrapper/index.tsx
  src/components/Payment/Btn/index.tsx
  src/components/Payment/Item/Item.styles.ts
  src/components/Payment/Item/Item.types.ts
  src/components/Payment/Item/index.tsx
  src/components/Payment/ItemList/ItemList.types.ts
  src/components/Payment/ItemList/index.tsx
  src/pages/Cart/index.tsx
  src/pages/Payment/index.tsx
Labels: Enhancement

#128 Feat: 로딩 애니메이션 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svg/loader.svg
  src/assets/svg/loader1.svg
  src/components/Common/Common.styles.ts
  src/components/Common/Loader.tsx
Labels: Enhancement

#130 Fix : 토큰 받아오기 오류 수정
  src/api/Auth/index.tsx
  src/api/Auth/query.ts
  src/components/Category/CategoryFilter/CategoryFilter.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterPopUp/index.tsx
  src/components/Category/CategoryFilter/CategoryFilterViewButton/CategoryFilterViewButton.styles.ts
  src/components/Category/CategoryFilter/CategoryFilterViewButton/index.test.tsx
  src/components/Category/CategoryFilter/CategoryFilterViewButton/index.tsx
  src/components/Category/CategoryFilter/index.tsx
  src/components/Category/CategoryItemWrapper/CategoryItemWrapper.styles.ts
  src/components/Category/CategoryItemWrapper/index.tsx
  src/hooks/useAxios.ts
  src/pages/Category/Category.styles.ts
  src/store/categoryViewAtom.ts
  src/utils/getTokenRefresh.ts
Labels: Enhancement

#131 Feat: 인증 경고창 추가, 상품 가격 표시 변경
  src/api/Auth/index.tsx
  src/components/Cart/CartItem/index.tsx
  src/components/Cart/Estimate/index.tsx
  src/components/Complete/CompleteMessage/CompleteMessage.types.ts
  src/components/Complete/CompleteMessage/index.tsx
  src/components/Complete/PaymentItems/index.tsx
  src/hooks/useAlert.ts
  src/hooks/useAxios.ts
  src/main.tsx
  src/pages/Cart/index.tsx
  src/pages/Complete/index.tsx
Labels: Enhancement

#132 Feat: Detail 페이지에 이미지 API 연동
  src/components/Detail/ProductGallery/ProductGallery.styles.ts
  src/components/Detail/ProductGallery/ProductGallery.types.ts
  src/components/Detail/ProductGallery/index.tsx
  src/components/DetailList/RoomItem/index.tsx
  src/components/DetailList/RoomList/RoomList.types.ts
  src/components/DetailList/RoomList/RoomList.utils.ts
  src/components/DetailList/RoomList/index.tsx
  src/pages/Detail/Detail.styles.ts
  src/pages/Detail/Detail.types.ts
  src/pages/Detail/index.tsx
Labels: Enhancement

#141 Feat : Results 페이지 외부 디자인 변경
  src/components/SearchListBanner/SearchList.styles.ts
  src/components/SearchListBanner/index.tsx
  src/pages/SearchList/SearchList.styles.ts
  src/pages/SearchList/index.tsx
Labels: Enhancement

#146 Feat: 로그인, capacity에 따른 버튼 비활성화
  src/components/Detail/ActionButtonGroup/index.tsx
  src/components/Detail/PriceDisplay/index.test.tsx
  src/components/Detail/QuantitySelector/index.tsx
  src/components/DetailList/RoomItem/index.test.tsx
  src/components/DetailList/RoomList/index.test.tsx
  src/pages/Detail/index.tsx
Labels: Refactoring

#150 Fix: Detail 페이지에서 이미지 없을 때 기본 이미지 안보이는 부분 수정
  src/components/Detail/ProductGallery/index.tsx
  src/components/Detail/QuantitySelector/QuantitySelector.styles.ts
  src/components/Detail/QuantitySelector/index.tsx
Labels: Fix

#152 Feat: CheckIn, Checkout date 삭제 로직 추가, myPage 라우팅 관련 수정
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
Labels: Fix, Enhancement

#163 Design: 이미지 크기 수정, 글자 간격 수정
  src/components/Detail/Calendar/Calendar.styles.ts
  src/components/Detail/PriceDisplay/PriceDisplay.styles.ts
  src/components/Detail/ProductDetails/ProductDetail.styles.ts
  src/components/Detail/QuantitySelector/QuantitySelector.styles.ts
  src/components/DetailList/ProductInfo/ProductInfo.styles.ts
  src/components/DetailList/ProductTitle/ProductTitle.styles.ts
  src/components/MyPage/MyOrder/MyOrderItem/MyOrder.styles.ts
Labels: Design

#165 Fix: 숙소 타입명 통일
  src/components/Category/CategoryFilter/CategoryFilter.constants.ts
  src/components/DetailList/ProductTitle/index.tsx
Labels: Fix

#167 Fix: 캘린더 날짜 선택 관련 수정
  src/components/Detail/Calendar/index.tsx
  src/components/DetailList/Card/Card.styles.ts
  src/components/DetailList/ProductImage/ProductImage.styles.ts
Labels: Fix

#168 Design: 로그인 로그아웃 노티문구 글씨크기 수정
  src/components/Signin/InputText/InputText.styles.ts
Labels: Design

#171 Docs: 리드미내 주요 구현 내용 추가
  README.md
Labels: Documentation

#177 Feat: 숙소/객실 페이지 테스트 코드 작성
  src/components/Detail/ActionButtonGroup/index.test.tsx
  src/components/Detail/PriceDisplay/index.test.tsx
  src/components/Detail/ProductDetails/ProductDetail.types.ts
  src/components/Detail/ProductDetails/index.test.tsx
  src/components/Detail/ProductDetails/index.tsx
  src/components/Detail/QuantitySelector/QuantitySelector.types.ts
  src/components/Detail/QuantitySelector/index.test.tsx
  src/components/Detail/StockStatusBaner/index.test.tsx
  src/components/DetailList/BookingCalendar/index.test.tsx
  src/components/DetailList/DateSelector/index.test.tsx
  src/components/DetailList/ProductImage/index.test.tsx
  src/components/DetailList/ProductInfo/index.test.tsx
  src/components/DetailList/ProductTitle/index.test.tsx
  src/pages/Detail/index.tsx
  src/pages/DetailList/index.tsx
Labels: Test, Chore
